### PR TITLE
chore: update evenio, remove unsafe send sync impl

### PR DESCRIPTION
**Pull request by Ruben2424**
- [x] `cargo update` to get newest [evenio](https://github.com/rj00a/evenio)
- [x] remove `Send` and `Sync` `impls`
- [ ] fix test

### CODE REVIEW

**Comment by andrewgazelka** [comment]
im gonna try to finish this up

**Comment by Ruben2424** [comment]
I just tried, but i dont' really understand what this test is for. So go ahead.

**Comment by andrewgazelka** [comment]
All tests seem to pass for me? 🤔

**Comment by Ruben2424** [comment]
> All tests seem to pass for me? 🤔

it is the https://github.com/andrewgazelka/hyperion/blob/main/crates/server/tests/many_players.rs test. It does not compile.

**Comment by Ruben2424** [comment]
There is the flag `#[cfg(target_os = "linux")]` in the test file. Are you on Mac?

**Comment by andrewgazelka** [comment]
oh i see. I am going to remove it I think it should be rewritten as it isn't written verywell atm

**Pull request merged**
