### PR TITLE
feat: remove unwraps

### PR DESCRIPTION
**Pull request by andrewgazelka**
remove unwraps from several locations in code. In the future, potentially we can have something that wraps `anyhow` (or maybe `thiserror` so we can respond to errors differently depending on the context.

### CODE REVIEW

**Comment by TestingPlant** [comment]
IMO we should allow expect so that there's better panic messages if they ever get triggered

**Comment by andrewgazelka** [comment]
> IMO we should allow expect so that there's better panic messages if they ever get triggered

Sure let's do that. however, I think we should try to use `expect` to a limited amount as well.

**Comment by andrewgazelka** [comment]
> IMO we should allow expect so that there's better panic messages if they ever get triggered

02834b7

**Comment by andrewgazelka** [comment]
closing for now

**Pull request closed without merging**
