### PR TITLE
Re-sync xp bar on changing skin

### PR DESCRIPTION
**Pull request by Kumpelinus**
Relates to #613

### CODE REVIEW

**Comment by andrewgazelka** [comment]
lgtm ... definitely want to profile if updating inventory often will become a performance issue with 10k players at ome point or not.

**Comment by Kumpelinus** [comment]
Probably adding a cooldown + making a player unable to switch class while in combat might make sense.

**Comment by andrewgazelka** [comment]
> Probably adding a cooldown + making a player unable to switch class while in combat might make sense.

players will only be able to switch classes once they get a number of points to be able to switch... so they won't be able to more than once an average every 5 minutes or so

(if you play diep.io / deeep io / mope io it is basically the same way)

I don't think we should add a cooldown for now

**Comment by Kumpelinus** [comment]
Oh, I thought they would maybe be able to switch back to a previous class. If you can't, it does not make sense to add it.

**Pull request merged**
