### PR TITLE
fix: remove broken linux compiler arg

### PR DESCRIPTION
**Pull request by eduxstad**
verification: ci and 
```
release-1  | 2024-03-25T01:17:16.565731Z  INFO server::system::player_join_world: Player Mathboy joined the world
```

### CODE REVIEW

**Comment by andrewgazelka** [comment]
I am good with this. However, not sure why this isn't working and I don't have an x86 machine by me (and don't want to use an emulator that takes 20 years)

Basing off of
https://github.com/bevyengine/bevy/blob/main/.cargo/config_fast_builds.toml

Maybe it would work if you substituted out for 
https://github.com/bevyengine/bevy/blob/main/.cargo/config_fast_builds.toml#L9

hmmmm still think it is weird it doesn't work. maybe the path to mold is different on x86? 🤔

**Comment by andrewgazelka** [comment]
alternatively I might just comment the majority of the `config.toml` out and let people set it on their own through their personal `RUSTFLAGS` might not be worth the hassle 🤷‍♂️

**Comment by eduxstad** [comment]
Error with the previous line 19:
 ```
➜  hyperion git:(main) docker compose up --build release
[+] Building 1.7s (21/23)                                                                                                                      docker:default
 => [release internal] load build definition from Dockerfile                                                                                             0.0s
 => => transferring dockerfile: 2.85kB                                                                                                                   0.0s
 => [release internal] load metadata for docker.io/library/alpine:3.19                                                                                   0.7s
 => [release internal] load .dockerignore                                                                                                                0.0s
 => => transferring context: 2B                                                                                                                          0.0s
 => [release internal] load build context                                                                                                                0.0s
 => => transferring context: 10.81kB                                                                                                                     0.0s
 => [release packages 1/2] FROM docker.io/library/alpine:3.19@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b                    0.0s
 => CACHED [release packages 2/2] RUN apk update &&     apk add --no-cache curl build-base openssl-dev pkgconfig musl-dev clang llvm lld mold            0.0s
 => CACHED [release builder  1/14] RUN curl https://sh.rustup.rs -sSf | sh -s -- -y &&    $HOME/.cargo/bin/rustup default nightly-2024-03-23             0.0s
 => CACHED [release builder  2/14] WORKDIR /app                                                                                                          0.0s
 => CACHED [release builder  3/14] COPY .cargo/config.toml .cargo/config.toml                                                                            0.0s
 => CACHED [release builder  4/14] COPY Cargo.toml Cargo.lock ./                                                                                         0.0s
 => CACHED [release builder  5/14] COPY chunk/Cargo.toml ./chunk/Cargo.toml                                                                              0.0s
 => CACHED [release builder  6/14] COPY chunk/src ./chunk/src                                                                                            0.0s
 => CACHED [release builder  7/14] COPY generator/Cargo.toml ./generator/Cargo.toml                                                                      0.0s
 => CACHED [release builder  8/14] COPY generator/build.rs ./generator/build.rs                                                                          0.0s
 => [release builder  9/14] COPY generator/generated.zip ./generator/generated.zip                                                                       0.0s
 => [release builder 10/14] COPY generator/src ./generator/src                                                                                           0.0s
 => [release builder 11/14] COPY generator-build/Cargo.toml ./generator-build/Cargo.toml                                                                 0.0s
 => [release builder 12/14] COPY generator-build/src ./generator-build/src                                                                               0.1s
 => [release builder 13/14] COPY server/Cargo.toml ./server/Cargo.toml                                                                                   0.0s
 => [release builder 14/14] COPY server/src ./server/src                                                                                                 0.0s
 => ERROR [release release 1/2] RUN --mount=type=cache,target=/cargo-home     --mount=type=cache,target=/usr/local/cargo/registry     --mount=type=cach  0.7s
------                                                                                                                                                        
 > [release release 1/2] RUN --mount=type=cache,target=/cargo-home     --mount=type=cache,target=/usr/local/cargo/registry     --mount=type=cache,target=/usr/local/cargo/git     --mount=type=cache,target=/app/target     cargo build --release --locked -p server:                                                       
0.687 error: failed to run `rustc` to learn about target-specific information                                                                                 
0.687                                                                                                                                                         
0.687 Caused by:                                                                                                                                              
0.687   process didn't exit successfully: `/root/.rustup/toolchains/nightly-2024-03-23-x86_64-unknown-linux-musl/bin/rustc - --crate-name ___ --print=file-names -Ctarget-cpu=native -Clink-arg=-fuse-ld=/usr/bin/mold link-arg=--ld-path=/usr/local/bin/mold -Zshare-generics=y -Zthreads=0 --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
0.687   --- stderr
0.687   error: multiple input filenames provided (first two filenames are `-` and `link-arg=--ld-path=/usr/local/bin/mold`)
0.687 
------
failed to solve: process "/bin/sh -c cargo build --release --locked -p server" did not complete successfully: exit code: 101
```

**Comment by andrewgazelka** [comment]
> Error with the previous line 19:
> 
> ```
> ➜  hyperion git:(main) docker compose up --build release
> [+] Building 1.7s (21/23)                                                                                                                      docker:default
> => [release internal] load build definition from Dockerfile                                                                                             0.0s
> => => transferring dockerfile: 2.85kB                                                                                                                   0.0s
> => [release internal] load metadata for docker.io/library/alpine:3.19                                                                                   0.7s
> => [release internal] load .dockerignore                                                                                                                0.0s
> => => transferring context: 2B                                                                                                                          0.0s
> => [release internal] load build context                                                                                                                0.0s
> => => transferring context: 10.81kB                                                                                                                     0.0s
> => [release packages 1/2] FROM docker.io/library/alpine:3.19@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b                    0.0s
> => CACHED [release packages 2/2] RUN apk update &&     apk add --no-cache curl build-base openssl-dev pkgconfig musl-dev clang llvm lld mold            0.0s
> => CACHED [release builder  1/14] RUN curl https://sh.rustup.rs -sSf | sh -s -- -y &&    $HOME/.cargo/bin/rustup default nightly-2024-03-23             0.0s
> => CACHED [release builder  2/14] WORKDIR /app                                                                                                          0.0s
> => CACHED [release builder  3/14] COPY .cargo/config.toml .cargo/config.toml                                                                            0.0s
> => CACHED [release builder  4/14] COPY Cargo.toml Cargo.lock ./                                                                                         0.0s
> => CACHED [release builder  5/14] COPY chunk/Cargo.toml ./chunk/Cargo.toml                                                                              0.0s
> => CACHED [release builder  6/14] COPY chunk/src ./chunk/src                                                                                            0.0s
> => CACHED [release builder  7/14] COPY generator/Cargo.toml ./generator/Cargo.toml                                                                      0.0s
> => CACHED [release builder  8/14] COPY generator/build.rs ./generator/build.rs                                                                          0.0s
> => [release builder  9/14] COPY generator/generated.zip ./generator/generated.zip                                                                       0.0s
> => [release builder 10/14] COPY generator/src ./generator/src                                                                                           0.0s
> => [release builder 11/14] COPY generator-build/Cargo.toml ./generator-build/Cargo.toml                                                                 0.0s
> => [release builder 12/14] COPY generator-build/src ./generator-build/src                                                                               0.1s
> => [release builder 13/14] COPY server/Cargo.toml ./server/Cargo.toml                                                                                   0.0s
> => [release builder 14/14] COPY server/src ./server/src                                                                                                 0.0s
> => ERROR [release release 1/2] RUN --mount=type=cache,target=/cargo-home     --mount=type=cache,target=/usr/local/cargo/registry     --mount=type=cach  0.7s
> ------                                                                                                                                                        
> > [release release 1/2] RUN --mount=type=cache,target=/cargo-home     --mount=type=cache,target=/usr/local/cargo/registry     --mount=type=cache,target=/usr/local/cargo/git     --mount=type=cache,target=/app/target     cargo build --release --locked -p server:                                                       
> 0.687 error: failed to run `rustc` to learn about target-specific information                                                                                 
> 0.687                                                                                                                                                         
> 0.687 Caused by:                                                                                                                                              
> 0.687   process didn't exit successfully: `/root/.rustup/toolchains/nightly-2024-03-23-x86_64-unknown-linux-musl/bin/rustc - --crate-name ___ --print=file-names -Ctarget-cpu=native -Clink-arg=-fuse-ld=/usr/bin/mold link-arg=--ld-path=/usr/local/bin/mold -Zshare-generics=y -Zthreads=0 --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
> 0.687   --- stderr
> 0.687   error: multiple input filenames provided (first two filenames are `-` and `link-arg=--ld-path=/usr/local/bin/mold`)
> 0.687 
> ------
> failed to solve: process "/bin/sh -c cargo build --release --locked -p server" did not complete successfully: exit code: 101
> ```

Hey. Sorry I didn't merge this in because I had a big change that I wanted to get in first (that modified a bit of stuff in the Dockerfile as well). Does 3ffcfc6 work for you (latest in `main`)?

**Comment by eduxstad** [comment]
yes it does work :+1:

**Pull request closed without merging**
