### PR TITLE
feat: check if monoio is using io uring (#84)

### PR DESCRIPTION
**Pull request by TestingPlant**
I haven't tested this in an environment that blocks io_uring, but in theory, this should work better than the original check.

### CODE REVIEW

**Comment by andrewgazelka** [comment]
oo this looks great

**Comment by TestingPlant** [comment]
Seems to work when using `sysctl kernel.io_uring_disabled=1` to disable io uring system wide

**Comment by andrewgazelka** [comment]
ok fixed for macOS

**Comment by andrewgazelka** [comment]
hmmmm weird behavior don't know why `fix?` commit is needed

**Pull request merged**
