### PR TITLE
feat: add amount to `/give`

### PR DESCRIPTION
**Pull request by CuzImClicks**

### CODE REVIEW

**Comment by andrewgazelka** [comment]
@CuzImClicks would you like me to finish this PR? or are you intending to finish it.

**Comment by CuzImClicks** [comment]
i think when i pushed it i forgot to commit my latest changes… when looking at it right now its missing the commands.rs file i think

**Comment by andrewgazelka** [comment]
is this ready for review?

**Comment by CuzImClicks** [comment]
> is this ready for review?

now it should be

**Comment by andrewgazelka** [comment]
good work :)

**Pull request merged**
